### ISSUE TITLE
Postman Collection needs to be updated due to new querys which need to be ran sequentially and depend on each other.

### ISSUE THREAD

**Issue by rohansikder** [mallyaaniruddh/software-design-project#53]
I will start this after Davids refactoring code is merged into develop.

**Comment by rohansikder** [comment]
- Implemented StateConverter for VehicleState with robust case-insensitive mappings.
- Enhanced error handling in StateConverter to manage unknown or invalid state types.
- Updated Vehicle entity to use StateConverter for mapping VehicleState attributes.
- Ensured compatibility with JSON polymorphic deserialization for VehicleState subclasses using @JsonTypeInfo and @JsonSubTypes.
- Refactored VehicleState subclasses (e.g., AvailableVehicleState, DamagedVehicleState) for consistency.
- Updated post man collection so **remaining booking querys/bugs need to be fixed**

**Comment by rohansikder** [comment]
**Postman Querys that still need fixing**

↳ Customize booking
  PUT http://localhost:8080/api/renting/customize_booking/An unexpected error occurred: Unable to find com.ul.vrs.entity.account.Customer with id ID2
 [400 Bad Request, 423B, 51ms]

↳ Make Payment
  PUT http://localhost:8080/api/renting/authenticate_payment/An unexpected error occurred: Unable to find com.ul.vrs.entity.account.Customer with id ID2 [404 Not Found, 537B, 36ms]

↳ Return and Open Gate
  PUT http://localhost:8080/api/renting/return_vehicle_and_open_gate/An unexpected error occurred: Unable to find com.ul.vrs.entity.account.Customer with id ID2 [400 Bad Request, 431B, 6ms]

↳ Return Vehicle
  PUT http://localhost:8080/api/renting/return_vehicle/An unexpected error occurred: Unable to find com.ul.vrs.entity.account.Customer with id ID2 [400 Bad Request, 417B, 7ms]

↳ Cancel booking
  DELETE http://localhost:8080/api/renting/cancel_booking/An unexpected error occurred: Unable to find com.ul.vrs.entity.account.Customer with id ID2 [400 Bad Request, 417B, 7ms]

**Comment by ivor11** [comment]
maybe errors will go away with the new auth changes in https://github.com/mallyaaniruddh/software-design-project/pull/55

**Comment by rohansikder** [comment]
Postman collection now works
